#!/usr/bin/env sh

. "$HOME/.nvm/nvm.sh"  # Load nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm


npx lint-staged --config ./lint-staged.config.js
npx vitest run --silent --passWithNoTests
